# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
    mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
    mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
    mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
    domain_name: example.com
    owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: 4920f1ccb8b1d503d26be91bb697f571264a60847d4ccacd46e90fdcffdbec7c318585e12b2a3ce8a177a2c8a69b600a57396463c057fc6def3e9ecbae8712d6

test:

  secret_key_base: 3249f36110e5643d6692b39fa6cf652765678873457ea3d46a18ae7375403412cbb5b4464a6df2b025f2ebe266fb3ebee2cf0f8692c9341dfacfd16e4e4aa05d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
